apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "todolist.fullname" . }}-ss
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "todolist.fullname" . }}-ss
  serviceName: {{ template "todolist.fullname" . }}-svc 
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: {{.Values.name}}-ss
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: library/nginx
        ports:
        - containerPort: 80
