apiVersion: apps/v1
kind: StatefulSet
metadata:
  app: todolist
  chart: 0.2.0
  release: {{ .Release.Name }}
  harness.io/release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: todolist
  serviceName: {{.Values.name}}-svc 
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: todolist
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: library/nginx
        ports:
        - containerPort: 80
