# K8S Deployments example
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
  labels:
    app: {{.Values.name}}
    release: {{ .Release.Name }}
    harness.io/release: {{ .Release.Name }}
    type: front-end
spec:
  template:
    metadata:
      name: {{.Values.name}}
      labels:
        app: {{.Values.name}}
        release: {{ .Release.Name }}
        harness.io/release: {{ .Release.Name }}
        type: front-end
    spec:
      imagePullSecrets:
        - name: {{.Values.name}}-dockercfg
      containers:
        - name: {{.Values.name}}-container
          image: {{.Values.image}}
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      harness.io/release: {{ .Release.Name }}
      type: front-end
